import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Syne, Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const syne = Syne({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-syne",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600"],
  style: ["normal", "italic"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${syne.variable} ${inter.variable}antialiased bg-[#F0E7FF]`}
      >
        <main className="max-w-[1280] mx-auto">
          <div className="flex flex-col min-h-screen bg-[#F0E7FF]">
            <Header />
              <Providers>{children}</Providers>
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
